myapp/urls.py
#// myapp/urls.py
 
from django.urls import path
from django.conf.urls import url
from . import views
 
app_name='myapp'
 
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # index.htmlにアクセスが来た場合、views.pyのindex関数の処理をする。

    url(r'^welcome/$', views.welcome, name='welcome'),
    url(r'^like/$', views.like, name='like'),
    url(r'^dislike/$', views.dislike, name='dislike'),
    url(r'^birthday/$', views.birthday, name='birthday'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')), # index.htmlに来た場合
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
# Create your views here.
from django.shortcuts import render # render関数
 
def index(request):
    return render(request,'index.html') # index.htmlを返す

def welcome(request): # welcome関数
	return render(request, 'welcome.html') # welcome.htmlを返す
 
def like(request): # like関数
    return render(request,'like.html') # like.htmlを返す
 
def dislike(request): # dislike関数
    return render(request,'dislike.html') # dislike.htmlを返す
 
def birthday(request): # birthday関数
    return render(request,'birthday.html') # birthday.htmlを返す

myapp/templates/index.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <link rel="stylesheet" href="{% static "css/style.css" %}"/>
 
        <script src="{% static 'javascript/sample.js' %}"></script>

        <title>我が家の愛犬ポチの日記</title>

        <script>
            function updateClock() {
              var now = new Date();
              var hour = now.getHours();
              var minute = now.getMinutes();
              var second = now.getSeconds();
              if ( hour < 10 ) hour = "0" + hour;
              if ( minute < 10 ) minute = "0" + minute;
              if ( second < 10 ) second = "0" + second;
              document.getElementById('myClock').innerHTML = hour+":"+minute+":"+second;
            }
            function start() {
              setInterval("updateClock();", 1000);
              updateClock();
            }
        </script>

        <style type="text/css">

            #jsalarmclock{
            font-family: Tahoma;
            font-weight: bold;
            font-size: 12px;
            }
            
            #jsalarmclock div{
            margin-bottom: 0.8em;
            }
            
            #jsalarmclock div.leftcolumn{
            float: left;
            width: 150px;
            font-size: 13px;
            background-color: lightyellow;
            clear: left;
            }
            
            #jsalarmclock span{
            margin-right: 5px;
            }
            
        </style>
    
        <script type="text/javascript">
        
        /***********************************************
        
        * JavaScript Alarm Clock- by JavaScript Kit (www.javascriptkit.com)
        * This notice must stay intact for usage
        * Visit JavaScript Kit at http://www.javascriptkit.com/ for this script and 100s more
        
        ***********************************************/
        
        var jsalarm={
            padfield:function(f){
                return (f<10)? "0"+f : f
            },
            showcurrenttime:function(){
                var dateobj=new Date()
                var ct=this.padfield(dateobj.getHours())+":"+this.padfield(dateobj.getMinutes())+":"+this.padfield(dateobj.getSeconds())
                this.ctref.innerHTML=ct
                this.ctref.setAttribute("title", ct)
                if (typeof this.hourwake!="undefined"){ //if alarm is set
                    if (this.ctref.title==(this.hourwake+":"+this.minutewake+":"+this.secondwake)){
                        clearInterval(jsalarm.timer)
                        window.location=document.getElementById("musicloc").value
                    }
                }
            },
            init:function(){
                var dateobj=new Date()
                this.ctref=document.getElementById("jsalarm_ct")
                this.submitref=document.getElementById("submitbutton")
                this.submitref.onclick=function(){
                    jsalarm.setalarm()
                    this.value="Alarm Set"
                    this.disabled=true
                    return false
                }
                this.resetref=document.getElementById("resetbutton")
                this.resetref.onclick=function(){
                jsalarm.submitref.disabled=false
                jsalarm.hourwake=undefined
                jsalarm.hourselect.disabled=false
                jsalarm.minuteselect.disabled=false
                jsalarm.secondselect.disabled=false
                return false
                }
                var selections=document.getElementsByTagName("select")
                this.hourselect=selections[0]
                this.minuteselect=selections[1]
                this.secondselect=selections[2]
                for (var i=0; i<60; i++){
                    if (i<24) //If still within range of hours field: 0-23
                    this.hourselect[i]=new Option(this.padfield(i), this.padfield(i), false, dateobj.getHours()==i)
                    this.minuteselect[i]=new Option(this.padfield(i), this.padfield(i), false, dateobj.getMinutes()==i)
                    this.secondselect[i]=new Option(this.padfield(i), this.padfield(i), false, dateobj.getSeconds()==i)
        
                }
                jsalarm.showcurrenttime()
                jsalarm.timer=setInterval(function(){jsalarm.showcurrenttime()}, 1000)
            },
            setalarm:function(){
                this.hourwake=this.hourselect.options[this.hourselect.selectedIndex].value
                this.minutewake=this.minuteselect.options[this.minuteselect.selectedIndex].value
                this.secondwake=this.secondselect.options[this.secondselect.selectedIndex].value
                this.hourselect.disabled=true
                this.minuteselect.disabled=true
                this.secondselect.disabled=true
            }
        }
        
        </script>

    </head>
 
    <body onload="start();">
        <h1>我が家の愛犬ポチの日記</h1>
 
        <div class="images">
            <img src="{% static "images/inu.png" %}" alt="">
        </div>

        <div class="audio">
            <audio controls>
            <source src="{% static "audio/dog.mp3" %}" type="audio/mp3">
            </audio>
        </div>
        
        <div class="Youtube">
            <p>
                <iframe width="560" height="315" src="https://www.youtube.com/embed/1zMDiUDk8Uo" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </p>
        </div>

        <div class="map">
            <p>
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6797.741327233442!2d130.53949637572006!3d31.582594425396316!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x353e674f658f5717%3A0x344cdb3777e0f44d!2z44CSODkwLTAwNTMg6bm_5YWQ5bO255yM6bm_5YWQ5bO25biC5Lit5aSu55S6!5e0!3m2!1sja!2sjp!4v1607070411824!5m2!1sja!2sjp" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
            </p>
        </div>

        <h2>うちの可愛い愛犬ポチを紹介するホームページです。</h2>
 
        <p><a href="{% url 'myapp:welcome' %}">可愛いわんちゃんがうちに来てくれました</a></p>
        <p><a href="{% url 'myapp:like' %}">ポチの好きな食べ物</a></p>
        <p><a href="{% url 'myapp:dislike' %}">ポチの嫌いな食べ物</a></p>
        <p><a href="{% url 'myapp:birthday' %}">ポチが１才になりました</a></p>

        <div id="myClock" align="center"
        style="font:bold 40pt Times New Roman; color:#008888;">
    </div>

    <form action="" method="">
        <div id="jsalarmclock">
        <div><div class="leftcolumn">Current Time:</div> <span id="jsalarm_ct" style="letter-spacing: 2px"></span></div>
        <div><div class="leftcolumn">Set Alarm:</div> <span><select></select> Hour</span> <span><select></select> Minutes</span> <span><select></select> Seconds</span></div>
        <div><div class="leftcolumn">Set Alarm Action:</div> <input type="text" id="musicloc" size="55" value="https://www.youtube.com/watch?v=FD9X71Y3XxA" /> <span style="font: normal 11px Tahoma">*Location of page to launch</span></div>
        <input type="submit" value="Set Alarm!" id="submitbutton" /> <input type="reset" value="reset" id="resetbutton" />
        </div>
    </form>
        
        
    <script type="text/javascript">
        
        jsalarm.init()
        
    </script>
      
      
    
    </body>
 
</html>